<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>DesktopTestRig.Build</RootNamespace>
    <AssemblyName>DesktopTestRig.Build</AssemblyName>
    <IsPackable>false</IsPackable>
    <EnableSourceLink>false</EnableSourceLink>
  </PropertyGroup>

</Project>
